=== couchbaselabs/couchbase-lite-tests/environment/aws/topology_setup/topology_schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema",
    "type": "object",
    "default": {
        "clusters": [
            {
                "server_count": 1
            }
        ],
        "sync_gateways": [
            {
                "cluster": 1
            }
        ],
        "logslurp": true
    },
    "additionalProperties": false,
    "properties": {
        "$schema": {
            "type": "string",
            "$comment": "Allows config files to declare they conform to this schema. Otherwise ignored."
        },
        "defaults": {
            "type": "object",
            "properties": {
                "cbs": {
                    "type": "object",
                    "properties": {
                        "version": {
                            "type": "string",
                            "default": "7.6.4"
                        }
                    }
                },
                "sgw": {
                    "type": "object",
                    "properties": {
                        "version": {
                            "type": "string",
                            "default": "3.2.2"
                        }
                    }
                },
                "es": {
                    "type": "object",
                    "properties": {
                        "version": {
                            "type": "string",
                            "default": "1.0.0"
                        }
                    }
                }
            },
            "additionalProperties": false
        },
        "clusters": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "server_count": {
                        "type": "integer",
                        "minimum": 1
                    },
                    "version": {
                        "type": "string",
                        "$comment": "The default here is 7.6.4 but can be changed with the schema defaults.cbs.version"
                    }
                },
                "required": ["server_count"],
                "additionalProperties": false
            }
        },
        "sync_gateways": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "cluster": {
                        "type": "integer",
                        "minimum": 0
                    },
                    "version": {
                        "type": "string",
                        "$comment": "The default here is 3.2.2 but can be changed with the schema defaults.sgw.version"
                    }
                },
                "required": ["cluster"],
                "additionalProperties": false
            }
        },
        "edge_servers": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "version": {
                        "type": "string",
                        "$comment": "The default here is 1.0.0 but can be changed with the schema defaults.es.version"
                    }
                },
                "additionalProperties": false
            }
        },
        "test_servers": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "location": {
                        "type": "string"
                    },
                    "cbl_version": {
                        "type": "string"
                    },
                    "platform": {
                        "type": "string",
                        "enum": [
                            "dotnet_windows",
                            "dotnet_macos",
                            "dotnet_ios",
                            "dotnet_android",
                            "jak_webservice",
                            "jak_desktop",
                            "jak_android",
                            "c_windows",
                            "c_macos",
                            "c_linux_x86_64",
                            "c_ios",
                            "c_android",
                            "swift_ios",
                            "js",
                            "reactnative",
                            "reactnative_android",
                            "reactnative_ios"
                        ]
                    },
                    "download": {
                        "type": "boolean",
                        "default": false
                    },
                    "ip_hint": {
                        "type": "string",
                        "default": ""
                    },
                    "dataset_version": {
                        "type": "string",
                        "default": "4.0"
                    }
                },
                "required": ["location", "cbl_version", "platform"],
                "additionalProperties": false
            }
        },
        "load_balancers": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "sync_gateways": {
                        "type": "array",
                        "items": {
                            "type": "integer",
                            "minimum": 0
                        },
                        "minItems": 1
                    }
                },
                "required": ["sync_gateways"],
                "additionalProperties": false
            }
        },
        "logslurp": {
            "type": "boolean"
        },
        "include": {
            "type": "string"
        },
        "tag": {
            "type": "string"
        }
    }
}

=== couchbaselabs/couchbase-lite-tests/jenkins/pipelines/QE/upg-sgw/topology.json
{
	"$schema": "../../../../environment/aws/topology_setup/topology_schema.json",
	"test_servers": [
		{
			"platform": "swift_ios",
			"cbl_version": "{{version}}",
			"location": "00008101-000E0519020A001E",
			"ip_hint": "10.100.150.115",
			"download": true
		}
	],
	"clusters": [
		{
			"server_count": 1
		}
	],
	"sync_gateways": [
		{
			"cluster": 0
		},
		{
			"cluster": 0
		}
	],
	"logslurp": true
}

=== couchbaselabs/couchbase-lite-tests/jenkins/pipelines/QE/multiplatform/topology_ios_android_system.json
{
    "$schema": "../../../../environment/aws/topology_setup/topology_schema.json",
    "test_servers": [
        {
            "platform": "jak_android",
            "cbl_version": "{{jak_android}}",
            "location": "56141JEBF18456",
            "ip_hint": "172.16.150.165",
            "download": true
        },
        {
            "platform": "jak_android",
            "cbl_version": "{{jak_android}}",
            "location": "45291VDJH01660",
            "ip_hint": "172.16.150.159",
            "download": true
        },
        {
            "platform": "jak_android",
            "cbl_version": "{{jak_android}}",
            "location": "51131XEKB7DBF1",
            "ip_hint": "172.16.150.163",
            "download": true
        },
        {
            "platform": "jak_android",
            "cbl_version": "{{jak_android}}",
            "location": "35101FDH20004D",
            "ip_hint": "172.16.150.164",
            "download": true
        },
        {
            "platform": "jak_android",
            "cbl_version": "{{jak_android}}",
            "location": "RZCWC0DAYLW",
            "ip_hint": "172.16.150.160",
            "download": true
        },
        {
            "platform": "jak_android",
            "cbl_version": "{{jak_android}}",
            "location": "RZCY60E6SCF",
            "ip_hint": "172.16.150.166",
            "download": true
        },
        {
            "platform": "jak_android",
            "cbl_version": "{{jak_android}}",
            "location": "RZCT31DWZEV",
            "ip_hint": "172.16.150.161",
            "download": true
        },
        {
            "platform": "jak_android",
            "cbl_version": "{{jak_android}}",
            "location": "R58M87C818K",
            "ip_hint": "172.16.150.163",
            "download": true
        },
        {
            "platform": "swift_ios",
            "cbl_version": "{{ios_version}}",
            "location": "00008110-000E544201D1401E",
            "ip_hint": "172.16.150.155",
            "download": true
        },
        {
            "platform": "swift_ios",
            "cbl_version": "{{ios_version}}",
            "location": "34fc12796a401aa57405c12c06c5b51491f9a68d",
            "ip_hint": "172.16.150.157",
            "download": true
        },
        {
            "platform": "swift_ios",
            "cbl_version": "{{ios_version}}",
            "location": "00008132-000C15A20E7A801C",
            "ip_hint": "172.16.150.151",
            "download": true
        },
        {
            "platform": "swift_ios",
            "cbl_version": "{{ios_version}}",
            "location": "0223a6ffabd4a4fded71f32351b498e04e2dacfe",
            "ip_hint": "172.16.150.156",
            "download": true
        },
        {
            "platform": "swift_ios",
            "cbl_version": "{{ios_version}}",
            "location": "23ee833a5d402a3c05ca7e1e366fd50dedd0c1e5",
            "ip_hint": "172.16.150.153",
            "download": true
        },
        {
            "platform": "swift_ios",
            "cbl_version": "{{ios_version}}",
            "location": "b5e82968a65bbaf925bd8a1cb65dc0da0b538b6a",
            "ip_hint": "172.16.150.154",
            "download": true
        },
        {
            "platform": "swift_ios",
            "cbl_version": "{{ios_version}}",
            "location": "00008122-001108DC2EB9801C",
            "ip_hint": "172.16.150.152",
            "download": true
        },
        {
            "platform": "swift_ios",
            "cbl_version": "{{ios_version}}",
            "location": "00008140-0006458A0C22801C",
            "ip_hint": "172.16.150.158",
            "download": true
        }
    ],
    "clusters": [
        {
            "server_count": 1
        },
        {
            "server_count": 1
        }
    ],
    "sync_gateways": [
        {
            "cluster": 0
        },
        {
            "cluster": 1
        }
    ],
    "logslurp": true
}

=== couchbaselabs/couchbase-lite-tests/jenkins/pipelines/QE/multiplatform/topology_ios_system.json
{
    "$schema": "../../../../environment/aws/topology_setup/topology_schema.json",
    "test_servers": [
        {
            "platform": "swift_ios",
            "cbl_version": "{{ios_version}}",
            "location": "00008110-000E544201D1401E",
            "ip_hint": "172.16.150.155",
            "download": true
        },
        {
            "platform": "swift_ios",
            "cbl_version": "{{ios_version}}",
            "location": "34fc12796a401aa57405c12c06c5b51491f9a68d",
            "ip_hint": "172.16.150.157",
            "download": true
        },
        {
            "platform": "swift_ios",
            "cbl_version": "{{ios_version}}",
            "location": "00008132-000C15A20E7A801C",
            "ip_hint": "172.16.150.151",
            "download": true
        },
        {
            "platform": "swift_ios",
            "cbl_version": "{{ios_version}}",
            "location": "0223a6ffabd4a4fded71f32351b498e04e2dacfe",
            "ip_hint": "172.16.150.156",
            "download": true
        },
        {
            "platform": "swift_ios",
            "cbl_version": "{{ios_version}}",
            "location": "23ee833a5d402a3c05ca7e1e366fd50dedd0c1e5",
            "ip_hint": "172.16.150.153",
            "download": true
        },
        {
            "platform": "swift_ios",
            "cbl_version": "{{ios_version}}",
            "location": "b5e82968a65bbaf925bd8a1cb65dc0da0b538b6a",
            "ip_hint": "172.16.150.154",
            "download": true
        },
        {
            "platform": "swift_ios",
            "cbl_version": "{{ios_version}}",
            "location": "00008122-001108DC2EB9801C",
            "ip_hint": "172.16.150.152",
            "download": true
        },
        {
            "platform": "swift_ios",
            "cbl_version": "{{ios_version}}",
            "location": "00008140-0006458A0C22801C",
            "ip_hint": "172.16.150.158",
            "download": true
        }
    ],
    "clusters": [
        {
            "server_count": 1
        },
        {
            "server_count": 1
        }
    ],
    "sync_gateways": [
        {
            "cluster": 0
        },
        {
            "cluster": 1
        }
    ],
    "logslurp": true
}

=== couchbaselabs/couchbase-lite-tests/topology.json
{
    "$schema": "environment/aws/topology_setup/topology_schema.json",
    "test_servers": [
        {
            "platform": "jak_android",
            "cbl_version": "3.3.0",
            "location": "R5CWB18X32M"
        },
        {
            "platform": "swift_ios",
            "cbl_version": "3.3.0",
            "location": "a30eb9b2916eb79ffc490fa27b5993c84596622d",
            "ip_hint": "192.168.117.104"
        }
    ],
    "defaults": {
        "cbs": {
            "version": "7.6.6"
        },
        "sgw": {
            "version": "3.2.3"
        }
    },
    "include": "environment/aws/topology_setup/default_topology.json",
    "tag": "multipeer_functional"
}

=== couchbaselabs/couchbase-lite-tests/jenkins/pipelines/QE/es/topologies/2es_1sgw_topology.json
{
    "$schema": "./topology_schema.json",
    "edge_servers": [
        {
            "version": "{{version}}"
        },
        {
            "version": "{{version}}"
        }
    ],
    "clusters": [
        {
            "server_count": 1
        }
    ],
    "sync_gateways": [
        {
            "cluster": 0
        }
    ],
    "logslurp": false
}

=== couchbaselabs/couchbase-lite-tests/jenkins/pipelines/QE/sgw/topology.json
{
    "$schema": "../../../../environment/aws/topology_setup/topology_schema.json",
    "test_servers": [
		{
			"platform": "swift_ios",
			"cbl_version": "{{version}}",
			"location": "00008101-000E0519020A001E",
			"ip_hint": "10.100.150.115",
			"download": true
		}
	],
    "clusters": [
        {
            "server_count": 2
        }
    ],
    "sync_gateways": [
        {
            "cluster": 0
        },
        {
            "cluster": 0
        },
        {
            "cluster": 0
        }
    ],
    "load_balancers": [
        {
            "sync_gateways": [0, 1, 2]
        }
    ],
    "logslurp": true
}
